# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: hla-1.2
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - bioconda::samtools=1.16
  - bioconda::bwa=0.7.17
  - bioconda::perl-excel-writer-xlsx
  - bioconda::perl-json-parse=0.62

